In [1]:
#Create a vector (array) of 1XN dimension representing N-dimensional feature vector of a sample. Write a program to compute
# the mean and variance of the elements present in the array.

import numpy as np
def compute_mean_variance(vector):
    mean = np.mean(vector)
    variance = np.var(vector)
    return mean, variance

N = 5  
low = 1  
high = 100
sample_vector = np.random.randint(low, high, size=N)  

# Compute mean and variance
mean, variance = compute_mean_variance(sample_vector)

print("Sample Vector:", sample_vector)
print("Mean:", mean)
print("Variance:", variance)

Sample Vector: [54 25 72 33 91]
Mean: 55.0
Variance: 594.0


In [2]:
#Create two vectors each of dimension 1XM each representing N-dimensional feature vector of a sample. Write a program to
#compute the Covariance between them.

import numpy as np
def compute_covariance(vector1, vector2):
    covariance_matrix = np.cov(vector1, vector2)
    covariance = covariance_matrix[0, 1]  # Extracting the covariance value from the covariance matrix
    return covariance

N = 4 
low = 1  
high = 50
sample_vector1 = np.random.randint(low,high,size=N)  # Creating a random vector of shape 1xM
sample_vector2 = np.random.randint(low,high,size=N)  # Creating another random vector of shape 1xM

# Compute covariance
covariance = compute_covariance(sample_vector1, sample_vector2)

print("Sample Vector 1:", sample_vector1)
print("Sample Vector 2:", sample_vector2)
print("Covariance between vectors:", covariance)

Sample Vector 1: [36 37 36 12]
Sample Vector 2: [18 32 37 17]
Covariance between vectors: 74.0


In [3]:
#Create two vectors each of dimension 1XN. Write a program to compute the Correlation between them.

import numpy as np
def compute_correlation(vector1, vector2):
    correlation_matrix = np.corrcoef(vector1, vector2)
    correlation = correlation_matrix[0, 1]  # Extracting the correlation value from the correlation matrix
    return correlation

N = 5 
low = 1  
high = 50
sample_vector1 = np.random.randint(low,high,size=N)  # Creating a random vector of shape 1xM
sample_vector2 = np.random.randint(low,high,size=N)  # Creating another random vector of shape 1xM

# Compute correlation
correlation = compute_correlation(sample_vector1, sample_vector2)

print("Sample Vector 1:", sample_vector1)
print("Sample Vector 2:", sample_vector2)
print("Correlation between vectors:", correlation)

Sample Vector 1: [14 19 24  2 43]
Sample Vector 2: [ 6  9  8  2 48]
Correlation between vectors: 0.9037690290260585


In [4]:
# Create a Matrix of MXN dimension representing the M-dimensional feature vector for N number of samples i. e (i,j)th
# entry of the matrix represents the ith feature of jth sample. Write a program to compute the covariance matrix and correlation 
# matrix. Comment on takeaways from these matrixes.

def compute_covariance_matrix(feature_matrix):
    covariance_matrix = np.cov(feature_matrix)
    return covariance_matrix

def compute_correlation_matrix(feature_matrix):
    correlation_matrix = np.corrcoef(feature_matrix)
    return correlation_matrix

M = 3  # Number of dimensions/features
N = 4  # Number of samples
feature_matrix = np.random.randint(50, size=(M, N))  
print("Feature matrix:")
print(feature_matrix)
covariance_matrix = compute_covariance_matrix(feature_matrix)
print("\nCovariance matrix:")
print(covariance_matrix)
correlation_matrix = compute_correlation_matrix(feature_matrix)
print("\nCorrelation matrix:")
print(correlation_matrix)

Feature matrix:
[[14  0 21 39]
 [14 40 27  1]
 [42 20  0 36]]

Covariance matrix:
[[ 263.         -238.33333333   59.66666667]
 [-238.33333333  281.66666667 -195.        ]
 [  59.66666667 -195.          353.        ]]

Correlation matrix:
[[ 1.         -0.87566741  0.19582428]
 [-0.87566741  1.         -0.61841431]
 [ 0.19582428 -0.61841431  1.        ]]
